# Generated by Django 5.0.6 on 2024-08-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmodel',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
