# Generated by Django 5.0.6 on 2024-08-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='medical_info',
        ),
    ]
