# Generated by Django 5.0.6 on 2024-08-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='problem',
            new_name='medical_info',
        ),
    ]
