# Generated by Django 5.0.6 on 2024-08-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_problem_patient_medical_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
    ]
