# Generated by Django 5.1.1 on 2024-10-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
